#!/usr/bin/env bash
# Native production-branch replay with offline dependencies and unchanged defaults.
set -euo pipefail
root="$(cd "$(dirname "$0")/../.." && pwd)"
source="${1:-$root/.github/workflows/scan-for-todo-comments.yaml}"
destination="${2:-$root/.github/workflows/scan-for-todo-comments-default-fixture.yaml}"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
yq -o=json '.' "$source" >"$work/source.json"
jq '
  .name = "📝 Scan for TODO Comments (Default Fixture)" |
  del(.jobs["dry-run"], .jobs.todos.permissions.issues) |
  .on.workflow_call.inputs["fixture-skip-app-token"] = {
    description:"Deliberately skip the offline dependency for the negative control",
    required:false, default:false, type:"boolean"} |
  .jobs.todos.steps |= map(
    if .name == "📝 Create issues from TODOs" then
      {name:"Prepare default-path offline dependencies", shell:"bash", env:{
        TODO_EXPECTED_TOKEN:"${{ github.token }}",
        TODO_EXPECTED_BEFORE:"${{ github.event.before || github.base_ref }}",
        TODO_EXPECTED_COMMITS:"${{ toJSON(github.event.commits) }}",
        TODO_EXPECTED_DIFF:"${{ github.event.pull_request.diff_url }}",
        TODO_EXPECTED_IGNORE:"${{ inputs.ignore }}",
        TODO_EXPECTED_PROJECT:"organization/devantler-tech/5",
        TODO_EXPECTED_PROJECT_SECRET:"offline-project-token",
        TODO_FIXTURE_SKIP_TOKEN:"${{ inputs.fixture-skip-app-token }}"},
        run:"bash .devantler-tech-actions/.github/tests/todo-production-default-fixture.sh prepare"},
      (.id = "fixture-scan" | .["continue-on-error"] = true)
    else . end) |
  .jobs.todos.steps += [{name:"Verify native default-path replay", if:"${{ always() }}", shell:"bash",
    env:{TODO_FIXTURE_OUTCOME:"${{ steps.fixture-scan.outcome }}",
      TODO_FIXTURE_SKIP_TOKEN:"${{ inputs.fixture-skip-app-token }}"},
    run:"bash .devantler-tech-actions/.github/tests/todo-production-default-fixture.sh verify"}]
' "$work/source.json" >"$work/fixture.json"
{
  printf '# Generated by .github/scripts/generate-todo-default-fixture.sh; do not edit.\n'
  yq -P '.' "$work/fixture.json"
} >"$destination"
