#!/usr/bin/env bash
# Preserve the production cleanup wrapper with a read-only token ceiling.
set -euo pipefail
root="$(cd "$(dirname "$0")/../.." && pwd)"
source="${1:-$root/.github/workflows/delete-workflow-runs.yaml}"
destination="${2:-$root/.github/workflows/delete-workflow-runs-readonly.yaml}"
work="$(mktemp)"
trap 'rm -f "$work"' EXIT
yq '
  .name = "🗑️ Delete Workflow Runs (Read-Only)" |
  .jobs.delete-runs.permissions = {"actions": "read", "contents": "read"}
' "$source" >"$work"
{
  printf '# Generated by .github/scripts/generate-cleanup-readonly.sh; do not edit.\n'
  cat "$work"
} >"$destination"
