#!/usr/bin/env bash
# Keep the complete TODO wrapper under a read-only token ceiling for catalogue CI.
set -euo pipefail
root="$(cd "$(dirname "$0")/../.." && pwd)"
source="${1:-$root/.github/workflows/scan-for-todo-comments.yaml}"
destination="${2:-$root/.github/workflows/scan-for-todo-comments-readonly.yaml}"
work="$(mktemp)"
trap 'rm -f "$work"' EXIT
yq '
  .name = "📝 Scan for TODO Comments (Read-Only)" |
  del(.jobs.todos.permissions.issues)
' "$source" >"$work"
{
  printf '# Generated by .github/scripts/generate-todo-readonly.sh; do not edit.\n'
  cat "$work"
} >"$destination"
