name: Login to GHCR
description: Login to GitHub Container Registry (GHCR)
author: devantler-tech
inputs:
  github-token:
    description: GitHub token with packages:read (or packages:write) scope
    required: true
runs:
  using: composite
  steps:
    - name: 🔑 Login to GHCR
      uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}
