#!/usr/bin/env bash
# Execute the pinned reporter's actual action script with a closed offline CLI plan.
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
mkdir "$work/bin"
git -C "$root" show 6d7a19f3b37722806610ade51da745d939eef7e5:actions/upsert-issue/action.yaml >"$work/action.yaml"
yq -r '.runs.steps[0].run' "$work/action.yaml" >"$work/action.sh"
cat >"$work/bin/gh" <<'SH'
#!/usr/bin/env bash
set -euo pipefail
[[ "$GH_TOKEN" == offline-fixture ]] || exit 99
jq -cn --args '$ARGS.positional' -- "$@" >> "$CALLS"
case "$1 $2" in
  'issue list')
    [[ "$MODE" != failed-read ]] || exit 23
    [[ "$MODE" != recover ]] || { printf '[{"number":99,"title":"Scheduled governance audits need attention"}]\n'; exit 0; }
    printf '[]\n'
    ;;
  'issue create')
    [[ "$MODE" == gap ]] || exit 99
    printf 'https://github.com/offline/fixture/issues/99\n'
    ;;
  'issue view')
    [[ "$MODE" == recover && "$3" == 99 ]] || exit 99
    printf 'OPEN\n'
    ;;
  'issue close')
    [[ "$MODE" == recover && "$3" == 99 ]] || exit 99
    ;;
  *) exit 99 ;;
esac
SH
chmod +x "$work/bin/gh"
for mode in gap recover failed-read; do
  : >"$work/calls"
  : >"$work/output"
  open=true
  [[ "$mode" != recover ]] || open=false
  status=0
  env -i PATH="$work/bin:$PATH" MODE="$mode" CALLS="$work/calls" GH_TOKEN=offline-fixture \
    TITLE='Scheduled governance audits need attention' \
    BODY='> 🤖 Generated by the Agentic Engineer

Offline outcome fixture.' BODY_FILE='' LABELS='' OPEN="$open" CLOSE_COMMENT='> 🤖 Generated by the Agentic Engineer

Complete successful audit.' REPO=offline/fixture GITHUB_ACTION_PATH="$root/actions/upsert-issue" \
    GITHUB_OUTPUT="$work/output" RETRY_MAX_ATTEMPTS=1 \
    bash "$work/action.sh" >"$work/log" 2>&1 || status=$?
  if [[ "$mode" == failed-read ]]; then
    [[ "$status" != 0 && ! -s "$work/output" ]] || {
      echo 'FAIL: failed search cleared a gap' >&2
      exit 1
    }
    jq -se 'length >= 1 and all(.[]; .[0:2] == ["issue","list"])' "$work/calls" >/dev/null
  else
    [[ "$status" == 0 ]] || {
      echo "FAIL: $mode returned $status" >&2
      exit 1
    }
    jq -se --arg mode "$mode" '
      def flag($name): .[index($name)+1];
      length == 3 and all(.[]; flag("--repo") == "offline/fixture") and
      .[0][0:2] == ["issue","list"] and
      (if $mode == "gap" then
        .[1][0:2] == ["issue","list"] and .[2][0:2] == ["issue","create"] and
        (.[2] | flag("--title")) == "Scheduled governance audits need attention" and
        (.[2] | flag("--body") | startswith("> 🤖 Generated by the Agentic Engineer"))
       else .[1][0:3] == ["issue","view","99"] and .[2][0:3] == ["issue","close","99"] and
        (.[2] | flag("--comment") | startswith("> 🤖 Generated by the Agentic Engineer")) end)
    ' "$work/calls" >/dev/null
    grep -Fxq 'issue-number=99' "$work/output"
    grep -Fxq 'issue-url=https://github.com/offline/fixture/issues/99' "$work/output"
  fi
  echo "PASS: offline report $mode"
done
