#!/usr/bin/env bash
# Routine reporting must not turn a skipped/incomplete audit into recovery.
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
[[ -f "$root/.github/workflows/governance-audits.yaml" ]] || {
  echo 'FAIL: routine workflow is missing' >&2
  exit 1
}
yq -o=json '.' "$root/.github/workflows/governance-audits.yaml" >"$work/source.json"
verify() {
  jq -e '
    def normalized: gsub("\\s+";" ") | sub(" $";"");
    (.on | keys == ["schedule","workflow_dispatch"]) and
    .on.schedule == [{cron:"17 6 * * *"}] and
    .on.workflow_dispatch.inputs["run-audit"].type == "boolean" and
    .on.workflow_dispatch.inputs["run-audit"].default == false and
    .permissions == {} and .env == null and .defaults == null and
    (.jobs | keys == ["admit","audit","report"]) and
    .jobs.admit.permissions == {contents:"read"} and
    (.jobs.admit.if | normalized) ==
      "github.repository == '\''devantler-tech/.github'\'' && github.ref == '\''refs/heads/main'\'' && (github.event_name == '\''schedule'\'' || github.event_name == '\''workflow_dispatch'\'')" and
    .jobs.admit.steps[1].with.ref == "${{ github.workflow_sha }}" and
    .jobs.admit.steps[1].with["persist-credentials"] == false and
    .jobs.admit.steps[2].run == "bash scripts/governance-audit-admission.sh" and
    .jobs.admit.outputs.enabled == "${{ steps.admission.outputs.enabled }}" and
    .jobs.admit.steps[2].env == {REQUESTED:"${{ inputs.run-audit }}"} and
    .jobs.audit.needs == ["admit"] and
    (.jobs.audit.if | normalized) == "needs.admit.outputs.enabled == '\''true'\''" and
    .jobs.audit.permissions == {contents:"read"} and
    .jobs.audit.steps[1].with.ref == "${{ github.workflow_sha }}" and
    .jobs.audit.steps[1].with["persist-credentials"] == false and
    .jobs.audit.steps[2].with == {
      "client-id":"${{ vars.APP_CLIENT_ID }}","private-key":"${{ secrets.APP_PRIVATE_KEY }}",
      owner:"devantler-tech","permission-metadata":"read","permission-administration":"read"} and
    .jobs.audit.steps[3].env == {
      GH_TOKEN:"${{ steps.audit-token.outputs.token }}",
      GH_INSTALLATION_ID:"${{ steps.audit-token.outputs.installation-id }}",
      GH_APP_CLIENT_ID:"${{ vars.APP_CLIENT_ID }}",GH_APP_PRIVATE_KEY:"${{ secrets.APP_PRIVATE_KEY }}"} and
    .jobs.audit.steps[3].run == "bash scripts/run-governance-audits.sh" and
    .jobs.report.needs == ["admit","audit"] and
    (.jobs.report.if | normalized) ==
      "!cancelled() && github.repository == '\''devantler-tech/.github'\'' && github.ref == '\''refs/heads/main'\'' && (github.event_name == '\''schedule'\'' || github.event_name == '\''workflow_dispatch'\'') && (needs.admit.result == '\''failure'\'' || needs.admit.outputs.enabled == '\''true'\'')" and
    .jobs.report.permissions == {issues:"write"} and .jobs.report.env == null and
    (.jobs.report.steps | length == 2) and
    .jobs.report.steps[0].if == "needs.admit.result != '\''success'\'' || needs.audit.result != '\''success'\''" and
    .jobs.report.steps[1].if == "needs.admit.result == '\''success'\'' && needs.audit.result == '\''success'\''" and
    .jobs.report.steps[0].with.open == "true" and .jobs.report.steps[1].with.open == "false" and
    (.jobs.report.steps[0].with | keys == ["body","open","repository","title"]) and
    (.jobs.report.steps[1].with | keys == ["body","close-comment","open","repository","title"]) and
    all(.jobs.report.steps[]; .with.repository == "devantler-tech/.github" and
      .with.title == "Scheduled governance audits need attention" and
      (.with.body | startswith("> 🤖 Generated by the Agentic Engineer")) and .env == null and
      (.uses | test("^devantler-tech/\\.github/actions/upsert-issue@[0-9a-f]{40}$"))) and
    all(.jobs[]; .["continue-on-error"] == null and .defaults == null) and
    all(.jobs[].steps[]; .shell == null and .["continue-on-error"] == null) and
    all(.jobs.admit.steps[],.jobs.audit.steps[]; .if == null and .["continue-on-error"] == null and
      (if has("uses") then (.uses | test("@[0-9a-f]{40}$")) else true end)) and
    (.jobs.admit.steps | length == 3) and (.jobs.audit.steps | length == 4)
  ' "$1" >/dev/null 2>&1
}
verify "$work/source.json" || {
  echo 'FAIL: routine audit lost its admission, read scope or failure reporting' >&2
  exit 1
}
while IFS=$'\t' read -r name mutation; do
  jq "$mutation" "$work/source.json" >"$work/mutated.json"
  if verify "$work/mutated.json"; then
    echo "FAIL: accepted $name" >&2
    exit 1
  fi
  echo "PASS: rejects $name"
done <<'CASES'
PR admission	.on.pull_request={}
default manual activation	.on.workflow_dispatch.inputs["run-audit"].default=true
untrusted admission	.jobs.admit.if="true"
mutable admission source	.jobs.admit.steps[1].with.ref="main"
skipped admission	.jobs.admit.steps[2].if="false"
forged output	.jobs.admit.outputs.enabled="true"
unguarded audit	.jobs.audit.if="true"
write App	.jobs.audit.steps[2].with["permission-administration"]="write"
partial census	.jobs.audit.steps[2].with.repositories=".github"
wrong installation	.jobs.audit.steps[3].env.GH_INSTALLATION_ID="1"
incomplete audit	.jobs.audit.steps[3].run="bash scripts/check-repository-admin-teams.sh"
ignored audit	.jobs.audit["continue-on-error"]=true
skipped reporter	.jobs.report.if="false"
reporter App key	.jobs.report.env.KEY="${{ secrets.APP_PRIVATE_KEY }}"
reporter content authority	.jobs.report.permissions.contents="write"
skipped audit closes issue	.jobs.report.steps[1].if="needs.audit.result != 'failure'"
cancelled audit reports recovery	.jobs.report.if="always()"
untrusted report recipient	.jobs.report.steps[0].with.repository="outside/fixture"
mutable reporter	.jobs.report.steps[0].uses="devantler-tech/.github/actions/upsert-issue@main"
masked report failure	.jobs.report.steps[0]["continue-on-error"]=true
skipped audit shell	.jobs.audit.steps[3].shell="true {0}"
ignored workflow shell	.defaults.run.shell="true {0}"
reporter App token	.jobs.report.steps[0].with["github-token"]="${{ secrets.APP_PRIVATE_KEY }}"
CASES
echo 'PASS: routine governance admission, read authority and report transitions are protected'
