#!/usr/bin/env bash
# Bind updater authority to reviewed main and prove complete, manifest-only preparation.
set -euo pipefail
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
fail() { echo "FAIL: $*" >&2; exit 1; }
workflow="$root/.github/workflows/refresh-gh-digests.yaml"
# shellcheck disable=SC2016 # GitHub expressions are literal contract values.
admission='${{ github.repository == '\''devantler-tech/.github'\'' && github.ref == '\''refs/heads/main'\'' && github.workflow_ref == '\''devantler-tech/.github/.github/workflows/refresh-gh-digests.yaml@refs/heads/main'\'' && (github.event_name == '\''schedule'\'' || github.event_name == '\''workflow_dispatch'\'') }}'
check_boundary() {
  yq -o=json '.' "$1" | jq -e --arg admission "$admission" '
    (keys | sort) == ["jobs","name","on","permissions"] and
    .permissions == {} and (.on | keys | sort) == ["schedule", "workflow_dispatch"] and
    .on.workflow_dispatch == null and .on.schedule == [{cron:"17 4 * * 1"}] and
    (.jobs | keys) == ["refresh"] and .jobs.refresh as $job |
    ($job | keys | sort) == ["concurrency","if","permissions","runs-on","steps","timeout-minutes"] and
    $job."runs-on" == "ubuntu-latest" and $job."timeout-minutes" == 10 and
    $job.if == $admission and $job.permissions == {contents:"read"} and
    $job.concurrency == {group:"refresh-gh-digests",queue:"max","cancel-in-progress":false} and
    $job.steps as $steps |
    ($steps | length) == 5 and all($steps[];
      (keys - ["name","id","if","uses","with","run"] | length) == 0) and
    ($steps[0] | del(.name)) == {
      uses:"step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1",
      with:{"egress-policy":"audit"}} and
    ([$steps[]|select(.id=="source")|{uses,with}] == [{
      uses:"actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1",
      with:{ref:"${{ github.workflow_sha }}","persist-credentials":false}}]) and
    ([$steps[]|select(.id=="prepare")|{run,if:(.if//null),tolerate:(."continue-on-error"//false)}] == [{
      run:"bash .github/scripts/prepare-gh-digest-update.sh",if:null,tolerate:false}]) and
    ([$steps|to_entries[]|select(.value.id=="prepare")|.key][0] <
     [$steps|to_entries[]|select(.value.id=="app-token")|.key][0]) and
    ([$steps[]|select(.id=="app-token")|{uses,if,with}] == [{
      uses:"actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1",
      if:"${{ steps.prepare.outputs.changed == '\''true'\'' }}",
      with:{"client-id":"${{ vars.APP_CLIENT_ID }}","private-key":"${{ secrets.APP_PRIVATE_KEY }}",
        owner:"devantler-tech",repositories:".github","permission-contents":"write","permission-pull-requests":"write"}}]) and
    ([$steps[]|select(.id=="pr")][0] as $pr |
      $pr.uses == "peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1" and
      $pr.if == "${{ steps.prepare.outputs.changed == '\''true'\'' }}" and
      $pr.with."sign-commits" == true and $pr.with.draft == true and
      $pr.with."add-paths" == ".scripts/gh-release-digests.tsv" and
      $pr.with.token == "${{ steps.app-token.outputs.token }}" and
      $pr.with."branch-token" == "${{ steps.app-token.outputs.token }}" and
      $pr.with.base == "main" and $pr.with.branch == "automation/gh-release-digests" and
      ($pr.with.title | startswith("fix(deps):")) and
      ($pr.with."commit-message" | startswith("fix(deps):")) and
      ($pr.with.body | startswith("> 🤖 Generated by the Agentic Engineer\n")))
  ' >/dev/null
}
check_boundary "$workflow" || fail 'updater source/credential/PR boundary is unsafe'
for mutation in admission token-scope persisted source signing draft paths write-token early-token tolerated fallback ambient-secret early-secret; do
  cp "$workflow" "$work/mutated.yaml"
  # shellcheck disable=SC2016 # Literal GitHub expressions in boundary controls.
  case "$mutation" in
    admission) yq -i '.jobs.refresh.if = true' "$work/mutated.yaml" ;;
    token-scope) yq -i '(.jobs.refresh.steps[]|select(.id=="app-token")).with.repositories = "ksail"' "$work/mutated.yaml" ;;
    persisted) yq -i '(.jobs.refresh.steps[]|select(.id=="source")).with."persist-credentials" = true' "$work/mutated.yaml" ;;
    source) yq -i '(.jobs.refresh.steps[]|select(.id=="source")).with.ref = "main"' "$work/mutated.yaml" ;;
    signing) yq -i '(.jobs.refresh.steps[]|select(.id=="pr")).with."sign-commits" = false' "$work/mutated.yaml" ;;
    draft) yq -i '(.jobs.refresh.steps[]|select(.id=="pr")).with.draft = false' "$work/mutated.yaml" ;;
    paths) yq -i '(.jobs.refresh.steps[]|select(.id=="pr")).with."add-paths" = "."' "$work/mutated.yaml" ;;
    write-token) yq -i '.jobs.refresh.permissions.contents = "write"' "$work/mutated.yaml" ;;
    early-token) yq -i '.jobs.refresh.steps |= sort_by(.id == "prepare")' "$work/mutated.yaml" ;;
    tolerated) yq -i '(.jobs.refresh.steps[]|select(.id=="prepare"))."continue-on-error" = true' "$work/mutated.yaml" ;;
    fallback) yq -i '(.jobs.refresh.steps[]|select(.id=="pr")).with.token = "${{ github.token }}"' "$work/mutated.yaml" ;;
    ambient-secret) yq -i '.env.APP_KEY = "${{ secrets.APP_PRIVATE_KEY }}"' "$work/mutated.yaml" ;;
    early-secret) yq -i '.jobs.refresh.steps[0] = {"name":"early token", "run":"echo $APP_KEY", "env":{"APP_KEY":"${{ secrets.APP_PRIVATE_KEY }}"}}' "$work/mutated.yaml" ;;
  esac
  if check_boundary "$work/mutated.yaml"; then fail "accepted $mutation regression"; fi
done
echo 'PASS: reviewed source, delayed repository-only token, signed draft and exact-path mutations'

mkdir -p "$work/repo/.scripts" "$work/repo/.github/scripts" "$work/repo/.github/workflows" \
  "$work/repo/actions/setup-agent-skills" "$work/repo/actions/update-agent-skills" "$work/bin"
cp "$root/.scripts/refresh-gh-digests.sh" "$root/.scripts/gh-release-digests.tsv" "$work/repo/.scripts/"
cp "$root/.github/scripts/prepare-gh-digest-update.sh" "$work/repo/.github/scripts/"
cp "$root/.github/workflows/update-agent-skills.yaml" "$work/repo/.github/workflows/"
for action in setup-agent-skills update-agent-skills; do
  cp "$root/actions/$action/action.yaml" "$work/repo/actions/$action/"
done
cat >"$work/bin/curl" <<'STUB'
#!/usr/bin/env bash
set -euo pipefail
[[ "$#" == 18 && "${18}" == https://github.com/cli/cli/releases/download/v2.90.0/gh_2.90.0_checksums.txt ]] || exit 90
printf called >>"$DOWNLOAD_CALLS"
cp "$CHECKSUMS" "${17}"
STUB
chmod +x "$work/bin/curl"
: >"$work/sums"
for pair in 'linux amd64 tar.gz a' 'linux arm64 tar.gz b' 'macOS amd64 zip c' 'macOS arm64 zip d'; do
  # shellcheck disable=SC2086
  set -- $pair
  printf '%s  gh_2.90.0_%s_%s.%s\n' "$(printf '%64s' '' | tr ' ' "$4")" "$1" "$2" "$3" >>"$work/sums"
done
git -C "$work/repo" init -q
git -C "$work/repo" add .scripts/refresh-gh-digests.sh .scripts/gh-release-digests.tsv \
  .github/scripts/prepare-gh-digest-update.sh .github/workflows/update-agent-skills.yaml \
  actions/setup-agent-skills/action.yaml actions/update-agent-skills/action.yaml
git -C "$work/repo" -c user.name=Fixture -c user.email=fixture@example.invalid -c commit.gpgsign=false commit -qm fixture
prepare() {
  (cd "$work/repo" && PATH="$work/bin:$PATH" CHECKSUMS="$work/sums" DOWNLOAD_CALLS="$work/downloads" \
    GITHUB_OUTPUT="$work/output" bash .github/scripts/prepare-gh-digest-update.sh) >"$work/log" 2>&1
}
prepare || { cat "$work/log"; fail 'healthy preparation failed'; }
if ! grep -qx 'version=2.90.0' "$work/output" || ! grep -qx changed=true "$work/output"; then
  fail 'wrong prepared version/outcome'
fi
[[ "$(git -C "$work/repo" diff --name-only)" == .scripts/gh-release-digests.tsv ]] || fail 'preparation changed another path'
git -C "$work/repo" add .scripts/gh-release-digests.tsv
git -C "$work/repo" -c user.name=Fixture -c user.email=fixture@example.invalid -c commit.gpgsign=false commit -qm populated
: >"$work/output"
prepare || fail 'idempotent preparation failed'
grep -qx changed=false "$work/output" || fail 'no-change outcome still authorizes token mint'
real_git="$(command -v git)"
{
  # shellcheck disable=SC2016 # These expansions run in the Git failure fixture.
  printf '%s\n' '#!/usr/bin/env bash' 'set -euo pipefail' \
    'if [[ "$1" == "${FAIL_GIT_READ:-}" ]]; then exit 128; fi'
  printf 'exec %q "$@"\n' "$real_git"
} >"$work/bin/git"
chmod +x "$work/bin/git"
for failed_read in status ls-files; do
  export FAIL_GIT_READ="$failed_read"
  : >"$work/output"
  if prepare; then fail "failed $failed_read read authorized preparation"; fi
  [[ ! -s "$work/output" ]] || fail 'failed Git read produced publication eligibility'
done
unset FAIL_GIT_READ
echo 'PASS: failed status and untracked-path reads stop without eligibility outputs'
cp "$work/repo/.scripts/gh-release-digests.tsv" "$work/healthy-manifest"
older_digest="$(printf '%64s' '' | tr ' ' e)"
for corruption in version platform architecture digest fields duplicate; do
  cp "$work/healthy-manifest" "$work/repo/.scripts/gh-release-digests.tsv"
  older_version=2.89.0 older_os=linux older_arch=amd64 older_hash="$older_digest" extra=''
  case "$corruption" in
    version) older_version=invalid ;;
    platform) older_os=windows ;;
    architecture) older_arch=s390x ;;
    digest) older_hash=invalid ;;
    fields) extra=$'\textra' ;;
  esac
  printf '%s\t%s\t%s\t%s%s\n' "$older_version" "$older_os" "$older_arch" "$older_hash" "$extra" \
    >>"$work/repo/.scripts/gh-release-digests.tsv"
  if [[ "$corruption" == duplicate ]]; then
    printf '2.89.0\tlinux\tamd64\t%s\n' "$older_digest" >>"$work/repo/.scripts/gh-release-digests.tsv"
  fi
  git -C "$work/repo" add .scripts/gh-release-digests.tsv
  git -C "$work/repo" -c user.name=Fixture -c user.email=fixture@example.invalid -c commit.gpgsign=false commit -qm "$corruption"
  : >"$work/output"
  if prepare; then fail "retained $corruption corruption authorized preparation"; fi
  grep -F 'Complete manifest validation failed' "$work/log" >/dev/null || {
    cat "$work/log"; fail 'retained-row rejection did not reach manifest validation';
  }
  [[ ! -s "$work/output" ]] || fail 'retained corruption produced eligibility outputs'
done
cp "$work/healthy-manifest" "$work/repo/.scripts/gh-release-digests.tsv"
git -C "$work/repo" add .scripts/gh-release-digests.tsv
git -C "$work/repo" -c user.name=Fixture -c user.email=fixture@example.invalid -c commit.gpgsign=false commit -qm restored
echo 'PASS: every retained row is validated before eligibility output'
: >"$work/downloads"
yq -i '.inputs."gh-version".default = "2.89.0"' "$work/repo/actions/setup-agent-skills/action.yaml"
if prepare; then fail 'conflicting default versions accepted'; fi
[[ ! -s "$work/downloads" ]] || fail 'conflicting defaults reached download'
git -C "$work/repo" checkout -- actions/setup-agent-skills/action.yaml
printf '\n# unrelated dirty work\n' >>"$work/repo/actions/setup-agent-skills/action.yaml"
if prepare; then fail 'unrelated dirty work accepted'; fi
echo 'PASS: exact declared version, four platform rows, idempotence and unrelated-change refusal'
