name: 🚀 Feature
description: Submit a new feature as a user story with acceptance criteria and a definition of done checklist.
title: "[feature]: "
type: Feature
projects:
  - devantler-tech/5
body:
  - type: markdown
    attributes:
      value: |
        Please ensure this enhancement isn't already requested by searching existing issues.

        Provide a clear user story and define acceptance criteria and the definition of done below.

  - type: textarea
    id: user_story
    attributes:
      label: User Story
      description: Use the standard agile story format.
      value: |
        **As a** [role],
        **I want** [an action or feature],
        **So that** [a reason or benefit].

        ```mermaid
        graph TD
          A[Role] --> B[System/Interface]
          B --> C[Action 1 in Feature]
          C --> D[Action 2 in Feature]
          D --> E[Action N in Feature]
          E --> F[Reason/Benefit 1]
          E --> G[Reason/Benefit 2]
          E --> H[Reason/Benefit N]
        ```
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Provide a task list of the conditions that must be satisfied. Each item should be a clear, testable outcome.
      value: |
        - [ ] Criteria 1: Describe the first acceptance criterion here.
        - [ ] Criteria 2: Describe the second acceptance criterion here.
        - [ ] Criteria 3: Describe additional criteria as needed.
    validations:
      required: true
