name: Example

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📄 Checkout
        uses: actions/checkout@v5

      - name: Run a one-line script
        run: echo "Hello from your new workflow!"
