#!/usr/bin/env bash
# import-actions-catalogue.sh — copy the devantler-tech/actions catalogue into this repository's
# layout (#235), so the import is reproducible from one recorded source commit.
#
# USAGE
#   scripts/import-actions-catalogue.sh <actions-checkout> <this-repository-root>
#
# Layout (decided on #164/#165):
#   <action>/                 -> actions/<action>/
#   .scripts/                 -> .scripts/            (actions reach it as ${GITHUB_ACTION_PATH}/../../.scripts)
#   .github/workflows/*.yaml  -> .github/workflows/   (except the source repository's own release and CodeQL drivers)
#   .github/{actions,tests,fixtures,scripts}/ -> same path here
#   README.md                 -> appended to README.md between catalogue markers
#
# Text rewrites move every in-repository reference to a composite action from `<action>/` to
# `actions/<action>/`. Everything else is copied byte for byte. Re-running replaces the previous
# import, so the result depends only on the source commit.
set -euo pipefail

src="${1:?usage: import-actions-catalogue.sh <actions-checkout> <this-repository-root>}"
dst="${2:?usage: import-actions-catalogue.sh <actions-checkout> <this-repository-root>}"
[[ -d "$src/.github/workflows" ]] || { echo "not an actions checkout: $src" >&2; exit 2; }
[[ -d "$dst/profile" && -d "$dst/workflow-templates" ]] || { echo "not a .github checkout: $dst" >&2; exit 2; }

names=()
while IFS= read -r n; do names+=("$n"); done < <(cd "$src" && for f in */action.yaml; do dirname "$f"; done | sort)
[[ "${#names[@]}" -ge 10 ]] || { echo "found only ${#names[@]} composite actions in $src" >&2; exit 2; }

# The source repository's own drivers are not part of the catalogue: this repository keeps its own
# release train and its default CodeQL setup (#165).
excluded_workflows=(active-release.yaml active-codeql.yaml)
begin_marker='<!-- BEGIN actions catalogue: generated by scripts/import-actions-catalogue.sh -->'
end_marker='<!-- END actions catalogue -->'

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

# This repository's own CI job survives the import: keep its text before the catalogue's ci.yaml
# replaces the file (dropping the merge-queue exclusion and harden-runner step a previous import
# added), then fold it back in under the single `CI - Required Checks` gate.
awk '/^  validate-manifests:$/ { on = 1; print; next } on && /^  [A-Za-z0-9_-]+:$|^[^ #]/ { exit } on { print }' \
  "$dst/.github/workflows/ci.yaml" |
  perl -0pe 's/^    if: "\$\{\{ github\.event_name != \x27merge_group\x27[^\n]*\n//m;
    s/^(    steps:\n)      - name: \S+ Harden Runner\n[^\n]*\n        with:\n          egress-policy: audit\n\n/$1/m; s/\n+\z/\n/' \
    >"$work/own-job.yaml"
grep -q '^    steps:$' "$work/own-job.yaml" ||
  { echo "no validate-manifests job in $dst/.github/workflows/ci.yaml" >&2; exit 2; }

# Remove a previous import so a re-run reproduces the source exactly.
rm -rf "$dst/actions" "$dst/.scripts" "$dst/.github/actions" "$dst/.github/tests" "$dst/.github/fixtures" \
  "$dst/.github/scripts"
if [[ -f "$dst/.github/imported-workflows.txt" ]]; then
  while IFS= read -r wf; do rm -f "$dst/.github/workflows/$wf"; done <"$dst/.github/imported-workflows.txt"
fi

mkdir -p "$dst/actions"
for n in "${names[@]}"; do cp -R "$src/$n" "$dst/actions/$n"; done
cp -R "$src/.scripts" "$dst/.scripts"
for d in actions tests fixtures scripts; do
  if [[ -d "$src/.github/$d" ]]; then cp -R "$src/.github/$d" "$dst/.github/$d"; fi
done
# The Release Please engine fixture tests the source repository's own release train (#165).
rm -rf "$dst/.github/tests/release-please"

# Repository-level configuration the catalogue's tooling reads from the root. This repository had
# none of these before the import.
for cfg in zizmor.yml .yamllint.yml .markdownlint.json .cspell.json .mega-linter.yml; do
  cp "$src/$cfg" "$dst/$cfg"
done
# The catalogue's contributor guide and history move with it. The changelog is history, so it is
# copied untouched. Agent instructions are merged into this repository's AGENTS.md by hand, because
# parts of the source file describe the source repository's own layout and release train.
cp "$src/CONTRIBUTING.md" "$dst/actions/CONTRIBUTING.md"
cp "$src/CHANGELOG.md" "$dst/actions/CHANGELOG.md"
# .gitignore entries are merged, never duplicated.
while IFS= read -r line; do
  grep -qxF -- "$line" "$dst/.gitignore" 2>/dev/null || printf '%s\n' "$line" >>"$dst/.gitignore"
done <"$src/.gitignore"
# Which commit this import reproduces, when the source is a Git checkout.
if src_commit="$(git -C "$src" rev-parse HEAD 2>/dev/null)"; then
  printf 'devantler-tech/actions@%s\n' "$src_commit" >"$dst/actions/.imported-from"
fi

: >"$dst/.github/imported-workflows.txt"
for wf in "$src"/.github/workflows/*.yaml; do
  base="${wf##*/}"
  case " ${excluded_workflows[*]} " in *" $base "*) continue ;; esac
  cp "$wf" "$dst/.github/workflows/$base"
  printf '%s\n' "$base" >>"$dst/.github/imported-workflows.txt"
done

# Rewrites. Each pattern is anchored on the character before the action name, so a name inside a
# longer word or an already-moved path is never touched.
export ALT
ALT="$(IFS='|'; printf '%s' "${names[*]}")"
rewrite_paths() {
  perl -0pi -e '
    my $n = $ENV{ALT};
    s{(uses:\s*\./)($n)(?=["\x27\s/]|$)}{$1actions/$2}gm;               # uses: ./<action>
    s{((?:\\)?["\x27])\./($n)(?=\\?["\x27])}{$1./actions/$2}g;            # "./<action>" in a query
    s{(?<![\w./-])\./($n)/}{./actions/$1/}g;                           # ./<action>/... in a command
    s{(\.devantler-tech-actions/)($n)(?=["\x27\s/]|$)}{$1actions/$2}gm;  # same-commit self-checkout
    s{(?<![\w./-])($n)/}{actions/$1/}g;                                  # <action>/... relative to the root
    s{(\$root/|\$\{root\}/|\$repo_root/|\$\{repo_root\}/)($n)/}{$1actions/$2/}g;
    s{(\$root/|\$\{root\}/|\$repo_root/|\$\{repo_root\}/)($n)(?=["\x27])}{$1actions/$2}g;             # $root/<action>"
    s{(\$\{\w+:-)($n)/}{$1actions/$2/}g;                              # ${var:-<action>/...}
    s{(GITHUB_WORKSPACE\}?/)($n)(?=/)}{$1actions/$2}g;                    # $GITHUB_WORKSPACE/<action>/...
    s{(-C\s+)($n)(?=\s|$)}{$1actions/$2}gm;                                # go -C <action>
    s{^([ \t]+)($n)([ \t]*)$}{$1actions/$2$3}gm;                         # a scope list, one path per line
    s{(\$fixture/|\$\{fixture\}/)($n)(?=[/"\x27])}{$1actions/$2}g;             # a throwaway copy of the layout
    s{(?<![\w*./-])\*/action\.yaml}{actions/*/action.yaml}g;             # enumerations of every action
  ' "$@"
}
# Composite actions sit one level deeper, so their shared scripts are two levels up.
rewrite_action_script_paths() {
  perl -0pi -e 's{(ACTION_PATH\}?|github\.action_path \}\})/\.\./\.scripts/}{$1/../../.scripts/}g' "$@"
  # A script inside an action directory that finds the repository root as its own parent now
  # needs one more level, so `root` still means the repository root the other rewrites assume.
  perl -0pi -e 's{(dirname "\$0"\)/\.\.)(?=")}{$1/..}g' "$@"
}
# Consumer-facing documentation names the new home. Workflow code is left alone: its remote pins
# name commits that exist only in devantler-tech/actions until #235's follow-up repoints them.
rewrite_docs() {
  perl -0pi -e '
    s{(?<![\w./-])devantler-tech/actions/\.github/workflows/}{devantler-tech/.github/.github/workflows/}g;
    s{(?<![\w./-])devantler-tech/actions/(?=[\w<])}{devantler-tech/.github/actions/}g;
    # URLs to files: a workflow signing identity, and blob/tree links. Issue URLs stay as history.
    s{https://github\.com/devantler-tech/actions/\.github/workflows/}{https://github.com/devantler-tech/.github/.github/workflows/}g;
    s{https://github\.com/devantler-tech/actions/(blob|tree)/main/\.github/}{https://github.com/devantler-tech/.github/$1/main/.github/}g;
    s{https://github\.com/devantler-tech/actions/(blob|tree)/main/([a-z][a-z0-9-]*)(?=[/)\s`"]|$)}{https://github.com/devantler-tech/.github/$1/main/actions/$2}gm;
  ' "$@"
}
# Bare issue numbers in imported Markdown name the source repository's issues, so they are qualified.
qualify_issue_refs() {
  perl -0pi -e 's{(?<![\w/&#-])#(\d{2,5})\b}{devantler-tech/actions#$1}g' "$@"
}
# Code that names the repository it runs from (an identity check on github.workflow_ref, a checkout
# of the workflow's own source, a self-test exclusion) now runs from this repository. Remote `uses:`
# pins keep naming devantler-tech/actions: their commits exist only there until #235's follow-up
# re-pins them. Issue references (`devantler-tech/actions#N`) and URLs stay as history.
rewrite_identity() {
  perl -pi -e '
    next if /^\s*(?:-\s*)?uses:\s*devantler-tech\/actions\//;
    s{(?<![\w./-])devantler-tech/actions/\.github/workflows/}{devantler-tech/.github/.github/workflows/}g;
    s{(?<![\w./-])devantler-tech/actions/(?=[a-z<])}{devantler-tech/.github/actions/}g;
    s{(?<![\w./-])devantler-tech/actions(?=[\x27"\s)\]`,:]|$)}{devantler-tech/.github}g;
  ' "$@"
}
text_files() {
  while IFS= read -r f; do if grep -Iq . "$f" 2>/dev/null; then printf '%s\n' "$f"; fi; done
}

files=()
while IFS= read -r f; do files+=("$f"); done < <(
  {
    find "$dst/actions" "$dst/.scripts" "$dst/.github/actions" "$dst/.github/tests" "$dst/.github/fixtures" \
      "$dst/.github/scripts" -type f ! -path "$dst/actions/CHANGELOG.md" 2>/dev/null
    sed "s|^|$dst/.github/workflows/|" "$dst/.github/imported-workflows.txt"
  } | text_files
)
rewrite_paths "${files[@]}"
# Identity rewrites apply only where the code names the repository it runs from: the imported
# workflows (not ci.yaml, whose one reference asserts the kept remote pins) and the tests and
# helper that check those identities. Everything else that names devantler-tech/actions is test
# fixture data or handles consumers' pins, which still name it until #239.
identity_files=()
while IFS= read -r wf; do
  [[ "$wf" == ci.yaml ]] || identity_files+=("$dst/.github/workflows/$wf")
done <"$dst/.github/imported-workflows.txt"
for f in .github/tests/test-enable-auto-merge-author-gate.sh .github/tests/test-world-at-ruin-required-regressions.sh \
  .github/scripts/resolve-world-at-ruin-regression-base.sh; do
  [[ -f "$dst/$f" ]] || { echo "identity rewrite target is missing: $f" >&2; exit 2; }
  identity_files+=("$dst/$f")
done
rewrite_identity "${identity_files[@]}"
action_files=()
while IFS= read -r f; do action_files+=("$f"); done < <(find "$dst/actions" -type f ! -name CHANGELOG.md | text_files)
# Every imported file that spells how an action reaches its shared scripts follows the move: the
# actions themselves, the scripts' usage notes, and the tests that assert the exact line.
rewrite_action_script_paths "${files[@]}"
doc_files=()
while IFS= read -r f; do doc_files+=("$f"); done < <(find "$dst/actions" -type f -name '*.md' ! -name CHANGELOG.md | text_files)

# The catalogue README joins this repository's README between markers, so README-based checks keep
# reading one README.md at the root. Only the catalogue half is imported text.
# Its top-level title becomes a section of this README, so the page keeps a single H1.
perl -pe 's/^# /## / if $. == 1' "$src/README.md" >"$work/catalogue.md"
rewrite_paths "$work/catalogue.md"
rewrite_docs "$work/catalogue.md" "${doc_files[@]}" "${action_files[@]}" "$dst"/.scripts/*.sh
qualify_issue_refs "$work/catalogue.md" "${doc_files[@]}"
# The catalogue's contributor guide moves to actions/, so the README's link follows it.
perl -0pi -e 's{\[CONTRIBUTING\.md\]\(CONTRIBUTING\.md\)}{[actions/CONTRIBUTING.md](actions/CONTRIBUTING.md)} or die "no CONTRIBUTING link in the catalogue README\n"' \
  "$work/catalogue.md"
{
  awk -v b="$begin_marker" '$0 == b { exit } { line[NR] = $0; n = NR }
    END { while (n > 0 && line[n] == "") n--; for (i = 1; i <= n; i++) print line[i] }' "$dst/README.md"
  printf '\n%s\n\n' "$begin_marker"
  cat "$work/catalogue.md"
  printf '\n%s\n' "$end_marker"
} >"$work/README.md"
cp "$work/README.md" "$dst/README.md"

# One test builds a throwaway repository with its own composite action at the root. That fixture
# follows the same layout move, or the enumeration it exercises finds nothing.
perl -0pi -e 's{(\$work/repo/)fixture-action}{$1actions/fixture-action}g; s{uses: \./fixture-action}{uses: ./actions/fixture-action}g' \
  "$dst/.github/tests/test-test-script-wiring.sh"

# Fold this repository's own job into the imported CI as a text edit, so every other line of the
# catalogue's CI stays byte for byte (a YAML round-trip would re-quote and re-space the file):
#   - the workflow keeps `edited` / `ready_for_review`, because the release contract judges the
#     pull request title;
#   - the job carries the same merge-queue exclusion as every other job, as the imported
#     merge-group isolation guard requires (this repository has no merge queue, so nothing is lost);
#   - the job starts with the same pinned harden-runner step every other job uses, as the imported
#     harden-runner-first guard requires;
#   - the gate needs it and reads its result, as the needs/JOB_RESULTS parity guard requires.
ci="$dst/.github/workflows/ci.yaml"
OWN="$work/own-job.yaml" perl -0pi -e '
  open(my $fh, "<", $ENV{OWN}) or die "own job: $!"; my $own = do { local $/; <$fh> };
  my ($harden) = /^(      - name: \S+ Harden Runner\n        uses: step-security\/harden-runner\@[^\n]+\n        with:\n          egress-policy: audit\n)/m
    or die "no harden-runner step to reuse\n";
  my ($exclusion) = /^(    if: "\$\{\{ github\.event_name != \x27merge_group\x27 && !startsWith\(github\.head_ref, \x27release-please--\x27\)[^\n]*\n)/m
    or die "no merge-queue exclusion to reuse\n";
  $own =~ s/^(  validate-manifests:\n    name: [^\n]*\n)/$1$exclusion/m or die "own job has no name\n";
  $own =~ s/^(    steps:\n)/$1$harden\n/m or die "own job has no steps\n";
  s/^on:\n  pull_request:\n/on:\n  pull_request:\n    types: [opened, synchronize, reopened, edited, ready_for_review]\n/m
    or die "no pull_request trigger\n";
  # The Release Please engine test exercises the source repository'"'"'s own release train, which
  # stays behind; the lifecycle guard in the same job is consumer-facing and stays.
  s/^(  test-release-please-semantics:\n(?:    [^\n]*\n)*?)    name: "\[Test\] Release Please - Commit Semantics"\n/$1    name: "[Test] Release PR Lifecycle Guard"\n/m
    or die "no Release Please semantics job\n";
  s/\n      - name: \S+ Setup Node\n        uses: actions\/setup-node\@[^\n]+\n        with:\n          node-version: \d+\n\n      - name: [^\n]+\n        run: npm ci --ignore-scripts --prefix \.github\/tests\/release-please\n\n      - name: [^\n]+\n        run: npm test --prefix \.github\/tests\/release-please\n/\n/
    or die "no Release Please engine steps\n";
  # The live OIDC self-test asserts the token names a workflow in the repository it runs from.
  s{^(            )devantler-tech/actions/\.github/workflows/\*\@\*\) ;;\n}{$1devantler-tech/.github/.github/workflows/*\@*) ;;\n}m
    or die "no live OIDC job_workflow_ref case arm\n";
  s/^(  ci-required-checks:\n)/$own\n$1/m or die "no ci-required-checks job\n";
  s/^(  ci-required-checks:\n(?:.*\n)*?    needs:\n(?:      - [^\n]+\n)+)/$1      - validate-manifests\n/m
    or die "no gate needs list\n";
  s/^(  ci-required-checks:\n(?:.*\n)*?          JOB_RESULTS: [^\n]*\n(?:            \$\{\{ needs\.[^\n]+\n)+)/$1            \${{ needs.validate-manifests.result }}\n/m
    or die "no JOB_RESULTS list\n";
' "$ci"

echo "imported ${#names[@]} composite actions and $(wc -l <"$dst/.github/imported-workflows.txt" | tr -d ' ') workflows"
