name: Publish NuGet packages
on:
  workflow_call:
    secrets:
      NUGET_API_KEY:
        required: true

jobs:
  publish-github:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 9
      - name: Get version from tag
        run: echo RELEASE_VERSION=${GITHUB_REF#refs/tags/v} >> $GITHUB_ENV
      - name: Pack
        run: dotnet pack --configuration Release /p:Version=${{ env.RELEASE_VERSION }}
      - name: Add GitHub Packages as NuGet Source
        run: dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
      - name: Push to GitHub Packages
        run: dotnet nuget push **/*.nupkg --source "github" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
  publish-nuget:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 9
      - name: Get version from tag
        run: echo RELEASE_VERSION=${GITHUB_REF#refs/tags/v} >> $GITHUB_ENV
      - name: Pack
        run: dotnet pack --configuration Release /p:Version=${{ env.RELEASE_VERSION }}
      - name: Push to NuGet
        run: dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
