name: GitOps Test

on:
  workflow_call:
  pull_request:
  merge_group:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 📑 Checkout
        uses: actions/checkout@v4
      - name: ⤵️ Install KSail
        run: |
          version=$(curl -s https://api.github.com/repos/devantler-tech/ksail/releases/latest | jq -r .tag_name)
          curl -L -o ksail https://github.com/devantler-tech/ksail/releases/download/$version/ksail-linux-amd64
          chmod +x ksail
          sudo mv ksail /usr/local/bin/ksail
      - name: 🛥️🐳 Provision cluster
        run: |
          ksail secrets import "${{ secrets.KSAIL_SOPS_KEY }}"
          ksail up
      - name: 🔥 Teardown cluster
        if: always()
        run: ksail down
